# Header
menu:
  Home: /
  #Archives: /archives

#rss: /atom.xml

menu_icon:
  Home: fa-home
  #Archives: fa-archive

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
#- tagcloud
- archive
- recent_posts
- links

# Links
links:
  淡忘~浅思: http://www.ido321.com
  前端开发手册: https://dwqs.gitbooks.io/frontenddevhandbook/content/

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Disqus
disqus_shortname:

#baidushare
baidushare: fasle

#duoshuo
duoshuo_shortname:

# Footer 显示文章的<footer>标签
isShowFooter: false