# Header
menu:
  Home: /
  Archives: /archives

menu_icon:
  Home: fa-home
  Archives: fa-archive

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  淡忘~浅思: http://www.ido321.com
  久艾网: http://www.92fenxiang.com
  前端开发手册: https://dwqs.gitbooks.io/frontenddevhandbook/content/

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:

# Disqus
disqus_shortname: